Header renderer
izachok/filmoteka-project pull request #25
Opened 2021-07-28 20:22 UTC by tskalska

2021-07-29 04:53 UTC, izachok requested changes

2021-07-29 04:53 UTC, izachok commented on src/js/components/pageState.js
> +
а для чего доп.методы? можем же просто обращаться pageState.isWatched = ...
А если методы и делаем, то должны обращаться к this.isWatched

2021-07-29 04:53 UTC, izachok commented on package.json
> +    "he": "^1.2.0"
для чего эта зависимость?

2021-07-29 04:53 UTC, izachok commented on src/js/components/renderLibrary.js
> +  console.log (navLibraryEls);
я так понимаю, что при нажатии на queue должен меняться цвет кнопки? У меня этого не происходит. По идее при нажатии еще должен меняться pageState

2021-07-29 04:53 UTC, izachok commented on src/js/components/search.js
> +  searchButtonEl: null,
а эти поля нужны или только ссылка на refs? Если первый доступ к ним идет после initSearch(), то вроде можно их тут не указывать, объявить только refs = {}

2021-07-29 04:53 UTC, izachok commented on package.json
> +    "he": "^1.2.0"
вроде не увидела по коду ее использование

2021-07-29 20:34 UTC, tskalska commented on src/js/components/pageState.js
> +
Поменяла (не перезаписывались значения когда создавала новые методы. Наверное не в этом была причина, т.к. сейчас работает)

2021-07-29 20:36 UTC, tskalska commented on package.json
> +    "he": "^1.2.0"
Ты знаешь, это не мое. Я ведь стягивала себе актуальный проект. Может ли это быть кем-то другим залито.

2021-07-29 20:37 UTC, tskalska commented on package.json
> +    "he": "^1.2.0"
Это было недоделано. Сейчас этим займусь.

2021-07-29 20:40 UTC, tskalska commented on src/js/components/search.js
> +  searchButtonEl: null,
Это не моя функция, я лишь только ее поправила, т.к. обращение было к элементам до их рендера. Попробовала сделать, как ты говоришь, все ломается. Так что предлагаю так оставить.

2021-07-30 05:22 UTC, izachok approved these changes

2021-07-30 05:22 UTC, merged